//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApi.WA.Account.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatApi.WA.Account.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reboot.
        /// </summary>
        internal static string AccountReboot {
            get {
                return ResourceManager.GetString("AccountReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setName.
        /// </summary>
        internal static string ChangeAccountName {
            get {
                return ResourceManager.GetString("ChangeAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setStatus.
        /// </summary>
        internal static string ChangeAccountStatus {
            get {
                return ResourceManager.GetString("ChangeAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string ChangeSettings {
            get {
                return ResourceManager.GetString("ChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiry.
        /// </summary>
        internal static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        internal static string GetAccountInformation {
            get {
                return ResourceManager.GetString("GetAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outputIP.
        /// </summary>
        internal static string GetOutputIP {
            get {
                return ResourceManager.GetString("GetOutputIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qr_code.
        /// </summary>
        internal static string GetQrCode {
            get {
                return ResourceManager.GetString("GetQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string GetSettings {
            get {
                return ResourceManager.GetString("GetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string GetStatus {
            get {
                return ResourceManager.GetString("GetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        internal static string RetrySynchronize {
            get {
                return ResourceManager.GetString("RetrySynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takeover.
        /// </summary>
        internal static string Takeover {
            get {
                return ResourceManager.GetString("Takeover", resourceCulture);
            }
        }
    }
}
