//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApi.WA.Dialogs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatApi.WA.Dialogs.Properties.Resourse", typeof(Resourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addGroupParticipant.
        /// </summary>
        internal static string AddParticipant {
            get {
                return ResourceManager.GetString("AddParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createLabel.
        /// </summary>
        internal static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to demoteGroupParticipant.
        /// </summary>
        internal static string DemoteParticipant {
            get {
                return ResourceManager.GetString("DemoteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog.
        /// </summary>
        internal static string GetDialog {
            get {
                return ResourceManager.GetString("GetDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialogs.
        /// </summary>
        internal static string GetDialogs {
            get {
                return ResourceManager.GetString("GetDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labelsList.
        /// </summary>
        internal static string GetLabels {
            get {
                return ResourceManager.GetString("GetLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joinGroup.
        /// </summary>
        internal static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labelChat.
        /// </summary>
        internal static string LabeledChat {
            get {
                return ResourceManager.GetString("LabeledChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaveGroup.
        /// </summary>
        internal static string LeaveGroup {
            get {
                return ResourceManager.GetString("LeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinChat.
        /// </summary>
        internal static string PinChat {
            get {
                return ResourceManager.GetString("PinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promoteGroupParticipant.
        /// </summary>
        internal static string PromoteParticipant {
            get {
                return ResourceManager.GetString("PromoteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readChat.
        /// </summary>
        internal static string ReadChat {
            get {
                return ResourceManager.GetString("ReadChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeChat.
        /// </summary>
        internal static string RemoveDialog {
            get {
                return ResourceManager.GetString("RemoveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeLabel.
        /// </summary>
        internal static string RemoveLabel {
            get {
                return ResourceManager.GetString("RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeGroupParticipant.
        /// </summary>
        internal static string RemoveParticipant {
            get {
                return ResourceManager.GetString("RemoveParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typing.
        /// </summary>
        internal static string SendTypingStatus {
            get {
                return ResourceManager.GetString("SendTypingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recording.
        /// </summary>
        internal static string SendVoiceRecordingStatus {
            get {
                return ResourceManager.GetString("SendVoiceRecordingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlabelChat.
        /// </summary>
        internal static string UnlabeledChat {
            get {
                return ResourceManager.GetString("UnlabeledChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpinChat.
        /// </summary>
        internal static string UnpinChat {
            get {
                return ResourceManager.GetString("UnpinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unreadChat.
        /// </summary>
        internal static string UnReadChat {
            get {
                return ResourceManager.GetString("UnReadChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateLabel.
        /// </summary>
        internal static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
    }
}
